# -*- coding: utf-8 -*-
"""gis_logic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/lamaww/gis-logic.372fed53-2cde-45f6-9fb0-f8d60e5cbc9c.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260425/auto/storage/goog4_request%26X-Goog-Date%3D20260425T113507Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3Dc82770d0bc3249983e188df0f894d74f534a43fb45148c7be514021bef389eb8a96b9dcdb3e4fc3fa9b5b77936dcf2b78e5852f45c836108e5cefbd7dd071de016c9c8eddffc9c57a4f4a1471acee6d5023d116272a68e6a5ab8075d119ebde3d1c4503c7cb8cd98261d7c4e6e4bbd893beb266b79451dad5a7cfcb0841167c8b631a89d250b2a9589775a971b897081eecf9a7d44a40730d643517cf93a00b36c229c5724e98916b31ad9af9a7696ca60d7b661840f3466e677818f88a7020a24cf5c87c7b16a909a527eb960b6beb6eb5a140d72b35a5d99e080734f569b4ec5d6eb5a396f3c8642129c1ec44b56a102fefe7707a359cb0237338c16edff16
"""

import json
from datetime import datetime
from shapely.geometry import Point, Polygon
from dateutil.relativedelta import relativedelta


class GISLayer:
    """Loads license data from JSON file and pre-processes geometries for performance."""
    def __init__(self, data_path="data/licenses.json"):
        # Added utf-8 encoding to support potential Arabic names in licenses
        with open(data_path, 'r', encoding='utf-8') as f:
            self.data = json.load(f)

        self.licenses = []
        # Pre-process licenses once at startup to save CPU cycles on Raspberry Pi
        for lic in self.data['licenses']:
            # Pre-build Polygon objects
            lic['poly_obj'] = Polygon([(lng, lat) for lat, lng in lic['polygon']])

            # Pre-parse dates to datetime objects
            lic['end_dt_obj'] = datetime.strptime(lic['end_date'], "%Y-%m-%d")

            # Pre-calculate warranty expiry (2 years after project end)
            lic['warranty_exp_obj'] = lic['end_dt_obj'] + relativedelta(months=24)

            self.licenses.append(lic)


class GPSSimulator:
    """Simulates GPS coordinates and timestamps per frame."""
    def __init__(self, data_path="data/licenses.json"):
        with open(data_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            self.points = data['gps_simulation']
        self.current_index = 0

    def next(self):
        if self.current_index < len(self.points):
            pt = self.points[self.current_index]
            self.current_index += 1
            return pt
        return self.points[-1]


class ResponsibilityEngine:
    """Evaluates who is responsible for a defect based on GPS and Warranty logic."""
    def __init__(self, gis_layer):
        self.gis_layer = gis_layer

    def decide(self, gps_point):
        # IMPORTANT: shapely expects (lng, lat)
        pothole_point = Point(gps_point['lng'], gps_point['lat'])
        sim_date = datetime.strptime(gps_point['simulated_date'], "%Y-%m-%d")

        for lic in self.gis_layer.licenses:
            # Check if the pothole is within the project's geographic boundary
            if lic['poly_obj'].contains(pothole_point):

                # Case A: Within warranty period (24 months after end_date)
                if sim_date <= lic['warranty_exp_obj']:
                    return ResponsibilityDecision("A", "Contractor", lic['contractor'])

                # Case B: Project exists but warranty has expired
                else:
                    return ResponsibilityDecision("B", "Municipality", "Warranty Expired")

        # Case C: No construction project recorded at this location
        return ResponsibilityDecision("C", "Municipality", "No Active Project")


class ResponsibilityDecision:
    """Structured output for the final responsibility decision."""
    def __init__(self, scenario, status, party):
        self.scenario = scenario
        self.status = status
        self.party = party

    def to_dict(self):
        return {
            "scenario": self.scenario,
            "status": self.status,
            "responsible_party": self.party
        }